services:
  ganache:
    build: .
    ports:
      - "8545:8545"
  solid_app:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - ganache
  # process_notification:
  #   build: ./server_modules/processNotifications
  #   depends_on:
  #     - ganache
  # clean_acl:
  #   build: ./server_modules/cleanExpiredACL
  #   depends_on:
  #     - ganache
